In [1]:
import numpy as np

a = np.random.randn(5,)
print(a)

[-1.95898523 -1.32048509  0.50938101 -0.15057444 -0.46978468]


In [2]:
print(a.T)

[-1.95898523 -1.32048509  0.50938101 -0.15057444 -0.46978468]


In [5]:
print(np.dot(a, a.T))

6.084143293593742


In [6]:
print(a.shape)

(5,)


In [11]:
a = np.random.randn(5,1)
print(a)

[[-0.18553012]
 [ 1.54807287]
 [ 0.08726162]
 [-0.82635   ]
 [ 0.81510286]]


In [12]:
print(a.T)

[[-0.18553012  1.54807287  0.08726162 -0.82635     0.81510286]]


In [13]:
print(np.dot(a, a.T))

[[ 0.03442143 -0.28721414 -0.01618966  0.15331281 -0.15122613]
 [-0.28721414  2.3965296   0.13508734 -1.27925001  1.26183863]
 [-0.01618966  0.13508734  0.00761459 -0.07210864  0.0711272 ]
 [ 0.15331281 -1.27925001 -0.07210864  0.68285432 -0.67356025]
 [-0.15122613  1.26183863  0.0711272  -0.67356025  0.66439268]]


In [14]:
print(np.dot(a.T, a))

[[3.78581262]]
